qlib_init:
  provider_uri: "~/.qlib/qlib_data/cn_data"
  region: cn

data_loader_config: &data_loader_config
  class: StaticDataLoader
  module_path: qlib.data.dataset.loader
  kwargs:
    config:
      feature: data/zzfea.pkl
      label: data/zzlab.pkl

model_config: &model_config
  input_size: 6
  hidden_size: 60
  num_layers: 2
  num_heads: 2
  use_attn: False
  dropout: 0.1

num_states: &num_states 1

tra_config: &tra_config
  num_states: *num_states
  hidden_size: 16
  tau: 1.0
  src_info: LR_TPE

task:
  model:
    class: TRAModel
    module_path: src/model.py
    kwargs:
      lr: 0.002
      n_epochs: 500
      max_steps_per_epoch: 100
      early_stop: 10
      seed: 1000
      logdir: output/zz500/cnn
      model_type: CNN
      model_config: *model_config
      tra_config: *tra_config
      lamb: 1.0
      rho: 0.99
      freeze_model: False
      model_init_state:
  dataset:
    class: MTSDatasetH
    module_path: src/dataset.py
    kwargs:
      handler:
        class: DataHandler
        module_path: qlib.data.dataset.handler
        kwargs:
          data_loader: *data_loader_config
      segments:
        train: [ 2018-01-02, 2021-12-31 ]
        valid: [ 2022-01-03, 2022-12-30 ]
        test: [ 2023-01-03, 2023-12-28 ]
      seq_len: 20
      horizon: 1
      num_states: *num_states
      batch_size: 512